### ISSUE TITLE
"Cannot connect to the remote site" with J3 connector

### ISSUE THREAD

**Issue by Bodge-IT** [akeeba/panopticon_connector_j3#5]
![image](https://github.com/akeeba/panopticon_connector_j3/assets/1881642/03f94365-3d85-47fb-a325-9444c29e1dd0)

I also get warning about a J4 plugin:
` The “Web Services - Installer” plugin is disabled on your site

Panopticon uses the Joomla! API Application services provided by the “Web Services - Installer” plugin to ensure that all necessary extensions are installed and published on your site.

Please go to your site's backend and click on System, Manage, Extensions. Search for the “Web Services - Installer” plugin and enable it. `

On an english J3.10.12 site, Panopticon 1.0.1 PHP 7.4.33 Plugin enabled and public. No 2FA, No html security.

url added from plugin: https://www.mydomainname.co.uk/panopticon_api

debug info:
![image](https://github.com/akeeba/panopticon_connector_j3/assets/1881642/ea339b1f-1ed5-4d2e-9e1b-a627b5f53ad7)

Same issue as before as far as I can tell.

**Comment by nikosdion** [comment]
There seemed to be a problem when trying to connect to sites which didn't have SEF URLs with URL rewriting enabled on Joomla! 3. This has been addressed in the [latest dev release](https://www.akeeba.com/download/panopticon-dev/1-0-1-dev202310231802.html). Please install and test.

Note that the first time you get an error, it might suggest that you use a different Endpoint URL in the form `https://www.example.com/index.php/panopticon_api`. Note the `index.php/` in there. **This is a manual action**. Panopticon will **NOT** do that for you, it will only present it as a suggestion.

Moreover, the connector would erroneously recommend the endpoint URL `https://www.example.com/index.php?/panopticon_api` (note the question mark) on some Joomla! 3 sites. This was replaced with the Joomla! 4 API URL by Panopticon, therefore you got an error. This is now caught by Panopticon when you try to create a new site and converted _automatically_ to the correct Endpoint URL in the form `https://www.example.com/index.php/panopticon_api`. This is an automatic action; there is no need for you to do anything.

**Comment by Bodge-IT** [comment]
Hi Nic, I may have misunderstood your first point.  SEF urls are turned on this site with rewrite enabled.
Nevertheless after the update and change of the url, the site definition has saved.  Thanks.

On that point about not saving if the connection can't be made, I disagree with you.  I get what you're saying but there's no reason the entry couldn't save and then highlight a connection problem someway.  Again, user expectations differ but I found that fact I couldn't just add all my sites first and then sort out broken connections later to be annoying.  Feedback FWiW.

**Comment by nikosdion** [comment]
I really do understand that you are thinking about this from your personal, very narrow, point of view, as well as that you're not thinking it through. I am afraid I am not afforded this luxury. I have to think about everyone's experience, and think it through. The reason y'all like using my software? That's it. That's the secret sauce!

When you add a site you don't just add a site; it performs the initial discovery of the Joomla! and PHP version, update availability, extensions list, extensions update availability, and checks for the existence of Akeeba Backup and Admin Tools for the integrations to work properly. 

If I would let you save without establishing a connection this would not be possible. As a result, your first experience after adding a site would be seeing that your site is "Unknown" Joomla! version, "Unknown" PHP version, has no extensions listed, therefore you cannot define their update schedule, no integration with Akeeba Backup, and no integration with Admin Tools. Yes, sure, this information fills in after 15' when the corresponding tasks run. Maybe far longer if you are running a bunch of updates which hog the queue due to their higher priority. Either way, the experience that you get as a user is that Panopticon is broken. Nobody would want to use this kind of software.

If you were able to add a site without checking the connection and there was any kind of connection error you would have an even worse time. Not only would the software appear broken, but there would be no indication that it can somehow correct itself. It would only show you that there was a communication error with the API. If you're lucky, you'd get an HTTP error code, or some HTTP response to look at and understand nothing about it. It would definitely be impossible to tell you what broke and how to fix it.

That's because the only thing you'd see would be the error response from an API request. We cannot check for _all_ the connectivity issues including whether the host resolves, if the TLS certificate is valid, if you are using a valid but self-signed TLS certificate, if there is an issue with your firewall, if the API can be accessed at all (even without authentication), if the necessary plugins are enabled etc. There's currently a dozen checks and they take a long time to run. We cannot spend that much time before _every single request to your site_ because it's impractical, it would make everything abysmally slow, and it would actually cause a lot more issues.

Even if a user had not given up at this point, it would be VERY hard for me to help them, as they could not provide any useful information for me to troubleshoot, let alone be able to offer them automatic suggestions in the software itself. This means that what is a 30 second fix with the automatic suggestions provided in Panopticon would be a multi-day saga. Even worse, there's only one of me. The more people would ask me for help, the fewer people and much slower I would be able to help. People would be upset, they would consider the software broken, and never come back.

Finally, let's talk about the fact that the reason we are having this discussion is that there was exactly one issue I didn't account for: some sites do not have a .htaccess which allows them to accept a URL like `https://www.example.com/panopticon_api` and need you to add `/index.php` in there like so: `https://www.example.com/index.php/panopticon_api`. If you were to try this altered Endpoint in the published version 1.0.0 you would see that it works. Hand on heart, do you think you'd be able to figure this out yourself? Even more poignantly, do you think you'd be able and/or willing to do that for dozens of sites? I believe not, and you'd think that Panopticon is broken because of your understandable frustration.

Therefore, I am not going to let you add sites without checking the connection.
